# Generated by Django 6.1.1 on 2026-09-15 00:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itemfactura',
            options={'ordering': ['id']},
        ),
    ]
